FROM php:8.2-apache

EXPOSE 80

RUN apt-get update && apt-get upgrade -y \
 && docker-php-ext-install pdo pdo_mysql \
 && docker-php-ext-enable  pdo pdo_mysql

ARG DB_CONNECTION_USER
ARG DB_CONNECTION_PASS
ARG DB_NAME
ARG DB_HOST

ENV DB_CONNECTION_USER=$DB_CONNECTION_USER
ENV DB_CONNECTION_PASS=$DB_CONNECTION_PASS
ENV DB_NAME=$DB_NAME
ENV DB_HOST=$DB_HOST