FROM php:8.2-apache

EXPOSE 80

RUN apt-get update && apt-get upgrade -y \
 && docker-php-ext-install pdo pdo_mysql \
 && docker-php-ext-enable  pdo pdo_mysql

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG DB_HOST

ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV DB_HOST=$DB_HOST