FROM php:8.2-apache

EXPOSE 80

RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libsqlite3-dev \
    libssl-dev \
    zlib1g-dev \
    libzip-dev \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql pdo_sqlite openssl \
 && docker-php-ext-enable openssl sqlite3 zip