USE event;
CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bdate DATE NOT NULL,
    event VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    promo VARCHAR(255) NOT NULL,
    venue_name VARCHAR(255) NOT NULL,
    venue_address_1 VARCHAR(255) NOT NULL,
    venue_address_2 VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    region VARCHAR(255) NOT NULL,
    postal INT NOT NULL,
    country VARCHAR(255) NOT NULL,
    capacity INT NOT NULL,
    attendance INT NOT NULL,
    performance VARCHAR(255) NOT NULL,
    time INT NOT NULL,
    contact_firstname VARCHAR(255) NOT NULL,
    contact_lastname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    number VARCHAR(255) NOT NULL,
    recorded TINYINT(1) NOT NULL,
    fileToUpload BLOB
);