services:

  phpapache:
    build:
      context: config/dockerfiles
      dockerfile: Dockerfile_phpapache
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_PORT: ${MYSQL_PORT}
        DB_HOST: ${DB_HOST}
    container_name: phpapache
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ".:/var/www/html"
    depends_on:
      - mysql
    networks:
      - app-network


  mysql:
    build:
      context: config/dockerfiles
      dockerfile: Dockerfile_mysql
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    build:
      context: config/dockerfiles
      dockerfile: Dockerfile_phpmyadmin
      args:
        DB_HOST: ${DB_HOST}
        MYSQL_PORT: ${MYSQL_PORT}
    container_name: phpmyadmin
    depends_on:
      - phpapache
      - mysql
    ports:
      - "${PMA_PORT}:80"
    networks:
      - app-network

networks:
  app-network: