services:

  phpapache:
    build:
      context: config/dockerfiles
      dockerfile: Dockerfile_phpapache
    container_name: phpapache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./config/apache.conf:/etc/apache2/sites-available/000-default.conf

  phpmyadmin:
    build:
      context: config/dockerfiles
      dockerfile: Dockerfile_phpmyadmin
    container_name: phpmyadmin
    ports:
      - "81:80"
    depends_on:
      - phpapache
      - mysql

  mysql:
    build:
      context: config/dockerfiles
      dockerfile: Dockerfile_mysql
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"
